My Submission for Mayhemheroes Bounty
mayhemheroes/memchr pull request #1
Opened 2022-05-15 19:09 UTC by mattjurenka

2022-06-07 23:17 UTC, xansec requested changes

2022-06-07 23:17 UTC, xansec commented on fuzz/Cargo.toml
> -cargo-features = ['named-profiles']
Can you comment on why these changes were necessary?

2022-06-09 13:03 UTC, mattjurenka commented
Rust recently stabilized the named profiles feature, causing Cargo.toml to not parse on nightly. The debug profile must be renamed as well as it is now a reserved keyword. I fixed this originally by just removing the two empty profiles, but I just added a commit reversing this deletion to better match the original project structure.

2022-06-09 14:00 UTC, xansec commented
Makes sense, thanks!

2022-06-09 14:00 UTC, merged